import "./globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "./AuthProvider";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Cart from "@/components/Cart/Cart";
import { BackDrop } from "@/components/ClientContext";

import ClientContextProvider from "@/components/ClientContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Klean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <ClientContextProvider>
          <Cart />
          <BackDrop />
          <Navbar />
          {children}
          <Footer />
        </ClientContextProvider>
      </html>
    </AuthProvider>
  );
}
