import "./globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "./AuthProvider";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Client from "@/components/ClientComponet";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Klean",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <Client>
            <Navbar />
            {children}
            <Footer />
          </Client>
        </body>
      </html>
    </AuthProvider>
  );
}
